title: "My Blogs Name"
author: "Default Author Name"
description: "Some short description of your blog can go here." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
theme: jekyll-theme-slate
